import prompts from 'prompts';
import { randomBytes } from 'crypto';
import { writeFile } from 'fs/promises';
import { join } from 'path';
import chalk from 'chalk';

const UUID_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

interface InitAnswers {
  cloud: 'commercial' | 'gcc-high' | 'dod';
  clientId: string;
  tenantId: string;
  redirectUri: string;
  scopes: string;
}

/**
 * Validate UUID format
 */
function isValidUUID(value: string): boolean | string {
  if (!value) return 'This field is required';
  if (!UUID_REGEX.test(value)) {
    return 'Invalid UUID format. Expected: 00000000-0000-0000-0000-000000000000';
  }
  return true;
}

/**
 * Interactive wizard to initialize Latch configuration
 */
export async function init(): Promise<void> {
  console.log(chalk.bold.cyan('\n🔐 Latch Configuration Wizard\n'));

  try {
    const answers = await prompts<string>([
      {
        type: 'select',
        name: 'cloud',
        message: 'Which Azure cloud environment?',
        choices: [
          {
            title: 'Azure Commercial',
            description: 'login.microsoftonline.com',
            value: 'commercial',
          },
          {
            title: 'Azure Government GCC-High (IL4)',
            description: 'login.microsoftonline.us',
            value: 'gcc-high',
          },
          {
            title: 'Azure Government DoD (IL5)',
            description: 'login.microsoftonline.us + dod-graph.microsoft.us',
            value: 'dod',
          },
        ],
        initial: 0,
      },
      {
        type: 'text',
        name: 'clientId',
        message: 'Azure AD Client ID (Application ID):',
        validate: isValidUUID,
      },
      {
        type: 'text',
        name: 'tenantId',
        message: 'Azure AD Tenant ID (Directory ID):',
        validate: isValidUUID,
      },
      {
        type: 'text',
        name: 'redirectUri',
        message: 'OAuth Redirect URI:',
        initial: 'http://localhost:3000/api/latch/callback',
      },
      {
        type: 'text',
        name: 'scopes',
        message: 'OAuth Scopes (space-separated):',
        initial: 'openid profile User.Read',
      },
    ]) as InitAnswers;

    // User cancelled
    if (!answers.cloud) {
      console.log(chalk.yellow('\n✗ Configuration cancelled'));
      process.exit(0);
    }

    // Generate cookie secret
    const cookieSecret = randomBytes(32).toString('base64');

    // Build .env.local content
    const envContent = `# Latch Configuration - ${getCloudName(answers.cloud)}
# Generated by @latch/cli on ${new Date().toISOString().split('T')[0]}

# Azure AD Application
LATCH_CLIENT_ID=${answers.clientId}
LATCH_TENANT_ID=${answers.tenantId}

# Cloud Environment
LATCH_CLOUD=${answers.cloud}

# OAuth Configuration
LATCH_SCOPES=${answers.scopes}
LATCH_REDIRECT_URI=${answers.redirectUri}

# Cookie Encryption Secret (NEVER commit this!)
LATCH_COOKIE_SECRET=${cookieSecret}

# Debug Mode (optional)
LATCH_DEBUG=false

# Next.js URL (used if LATCH_REDIRECT_URI not set)
NEXTAUTH_URL=http://localhost:3000
`;

    // Write to .env.local
    const envPath = join(process.cwd(), '.env.local');
    await writeFile(envPath, envContent, 'utf-8');

    // Success message
    console.log();
    console.log(chalk.green('✓ Configuration complete!'));
    console.log();
    console.log(chalk.bold('Created:'), chalk.cyan('.env.local'));
    console.log();
    console.log(chalk.bold('Next steps:'));
    console.log('  1. ' + chalk.dim('Review your .env.local file'));
    console.log('  2. ' + chalk.dim('Create API routes in app/api/latch/'));
    console.log('  3. ' + chalk.dim('Wrap your app with <LatchProvider>'));
    console.log('  4. ' + chalk.dim('Run') + ' pnpm dev ' + chalk.dim('to start'));
    console.log();

    if (answers.cloud !== 'commercial') {
      console.log(chalk.yellow('⚠  Government Cloud Notes:'));
      console.log(chalk.dim('  • Register your app at https://portal.azure.us'));
      console.log(chalk.dim('  • Do NOT use .com Graph URLs in scopes'));
      if (answers.cloud === 'dod') {
        console.log(chalk.dim('  • FIPS mode may be required (--force-fips)'));
      }
      console.log();
    }
  } catch (error) {
    console.error(chalk.red('\n✗ Error during initialization:'), error);
    process.exit(1);
  }
}

/**
 * Get friendly cloud name
 */
function getCloudName(cloud: string): string {
  const names: Record<string, string> = {
    commercial: 'Azure Commercial',
    'gcc-high': 'Azure Government GCC-High',
    dod: 'Azure Government DoD',
  };
  return names[cloud] || cloud;
}
